#!/bin/bash

export TEST_KEY_ENV="yep"

export TEST_KEY_ENV_SHORT=123
export TEST_KEY_ENV_INT=456
export TEST_KEY_ENV_LONG=789
export TEST_KEY_ENV_BOOLEAN=true

export TEST_KEY_ENV_es_CL="muchas gracias"
export TEST_KEY_ENV_en_US="many thanks"
export TEST_KEY_ENV_pt_BR="muito obrigado"


./sbt -v -213
